<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.targets" />

  <PropertyGroup>
    <LangVersion>$(CommonLangVersion)</LangVersion>
    <NoWarn>$(NoWarn);NU1605;IDE0079</NoWarn>
    <OutputType>library</OutputType>
    <TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <PackageId></PackageId>
    <AssemblyVersion>$(ReleaseVersion)</AssemblyVersion>
    <FileVersion>$(ReleaseVersion)</FileVersion>
    <AssemblyName>WinServiceInstaller</AssemblyName>
    <RootNamespace>WinServiceInstaller</RootNamespace>
    <StartupObject></StartupObject>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);TRACE;RELEASE</DefineConstants>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.System.Configuration.Install" Version="1.1.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="Microsoft.NETCore.Targets" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="runtime.native.System" Version="4.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Security.Permissions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'NET48'">
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows' or '$(TargetFramework)'=='net8.0-windows' or '$(TargetFramework)'=='net9.0-windows'">
    <PackageReference Include="Core.System.ServiceProcess" Version="2.0.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.10" />
  </ItemGroup>

</Project>
