<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\Common.targets" />

	<PropertyGroup>
	    <LangVersion>$(CommonLangVersion)</LangVersion>
		<TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
		<LangVersion>$(CommonLangVersion)</LangVersion>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows|AnyCPU'">
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows|AnyCPU'">
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net48|AnyCPU'">
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows|AnyCPU'">
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows|AnyCPU'">
	  <NoWarn>1701;1702;CA1510</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
		<PackageReference Include="Microsoft.NETCore.Targets" Version="5.0.0" />
		<PackageReference Include="runtime.native.System" Version="4.3.1" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
	</ItemGroup>
</Project>
