<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.targets" />

  <PropertyGroup>
    <LangVersion>$(CommonLangVersion)</LangVersion>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <LangVersion>$(CommonLangVersion)</LangVersion>
    <DefineConstants>$(DefineConstants);TRACE;RELEASE</DefineConstants>
    <Authors>YaR</Authors>
    <Company />
    <Product>WebDAVCloudMailRu</Product>
    <Copyright>MIT License, Copyright (c) 2025 YaR229 and Contributors</Copyright>
    <Description>WebDAV emulator for RU-clouds: Cloud.Mail.Ru &amp; Disk.Yandex.Ru</Description>
    <PackageId>WebDAVCloudMailRu</PackageId>
    <AssemblyVersion>$(ReleaseVersion)</AssemblyVersion>
    <FileVersion>$(ReleaseVersion)</FileVersion>
    <Version>$(ReleaseVersion)</Version>
    <AssemblyName>wdmrc</AssemblyName>
    <RootNamespace>YaR.Clouds.Console</RootNamespace>
    <StartupObject></StartupObject>
    <ApplicationIcon>cloud.ico</ApplicationIcon>
    <PackageProjectUrl>https://github.com/ZZZConsulting/WebDavMailRuCloud</PackageProjectUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <Title>WebDAV emulator for RU-clouds: Cloud.Mail.Ru &amp; Disk.Yandex.Ru</Title>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="cloud.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="HttpToSocks5Proxy" Version="1.4.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="Microsoft.NETCore.Targets" Version="5.0.0" />
    <PackageReference Include="runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.native.System" Version="4.3.1" />
    <PackageReference Include="runtime.native.System.Net.Http" Version="4.3.1" />
    <PackageReference Include="runtime.native.System.Security.Cryptography.Apple" Version="4.3.1" />
    <PackageReference Include="runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" Version="4.3.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="9.0.10" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.10" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.1" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.OpenSsl" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Security.Permissions" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hasher\Hasher.csproj" />
    <ProjectReference Include="..\MailRuCloud\MailRuCloudApi\YaR.Clouds.csproj" />
    <ProjectReference Include="..\MailRuCloud\TwoFA\UI\MailRuCloudApi.TwoFA.Console\MailRuCloudApi.TwoFA.Console.csproj" />
    <ProjectReference Include="..\MailRuCloud\TwoFA\UI\MailRuCloudApi.TwoFA.File\MailRuCloudApi.TwoFA.File.csproj" />
    <ProjectReference Include="..\NWebDav\NWebDav.Server.HttpListener\NWebDav.Server.HttpListener.csproj" />
    <ProjectReference Include="..\NWebDav\NWebDav.Server\NWebDav.Server.csproj" />
    <ProjectReference Include="..\WebDAV.Uploader\WDMRC.Console.Client.csproj" />
    <ProjectReference Include="..\WebDavMailRuCloudStore\WebDavStore.csproj" />
    <ProjectReference Include="..\WinServiceInstaller\WinServiceInstaller.csproj" />

    <ProjectReference Condition="'$(TargetFramework)' == 'never NET48'" Include="..\MailRuCloud\TwoFA\UI\MailRuCloudApi.TwoFA.Dialog\MailRuCloudApi.TwoFA.Dialog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\launchSettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="wdmrc.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
